-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 01:29:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `Airid` INT NOT NULL,
  `Airname` VARCHAR(45) NOT NULL,
  `Aircity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Airid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Eid` INT NOT NULL,
  `Ename` VARCHAR(45) NOT NULL,
  `Eage` VARCHAR(45) NOT NULL,
  `Esal` VARCHAR(45) NOT NULL,
  `Ejob` VARCHAR(45) NOT NULL,
  `Eaddr` VARCHAR(45) NOT NULL,
  `Airport_Airid` INT NOT NULL,
  PRIMARY KEY (`Eid`),
  INDEX `fk_Employee_Airport_idx` (`Airport_Airid` ASC),
  CONSTRAINT `fk_Employee_Airport`
    FOREIGN KEY (`Airport_Airid`)
    REFERENCES `mydb`.`Airport` (`Airid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `Pid` INT NOT NULL,
  `Pname` VARCHAR(45) NOT NULL,
  `Page` VARCHAR(45) NOT NULL,
  `Paddr` VARCHAR(45) NOT NULL,
  `Pcountry` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FlightTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FlightTime` (
  `Flight_no` INT NOT NULL,
  `Arrival` VARCHAR(45) NOT NULL,
  `Departure` VARCHAR(45) NOT NULL,
  `Flight_name` VARCHAR(45) NOT NULL,
  `Airport_Airid` INT NOT NULL,
  PRIMARY KEY (`Flight_no`),
  INDEX `fk_FlightTime_Airport1_idx` (`Airport_Airid` ASC),
  CONSTRAINT `fk_FlightTime_Airport1`
    FOREIGN KEY (`Airport_Airid`)
    REFERENCES `mydb`.`Airport` (`Airid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Tno` INT NOT NULL,
  `Seat` VARCHAR(45) NOT NULL,
  `Class` VARCHAR(45) NOT NULL,
  `Price` VARCHAR(45) NOT NULL,
  `Passenger_Pid` INT NOT NULL,
  `FlightTime_Flight_no` INT NOT NULL,
  PRIMARY KEY (`Tno`),
  INDEX `fk_Ticket_Passenger1_idx` (`Passenger_Pid` ASC),
  INDEX `fk_Ticket_FlightTime1_idx` (`FlightTime_Flight_no` ASC),
  CONSTRAINT `fk_Ticket_Passenger1`
    FOREIGN KEY (`Passenger_Pid`)
    REFERENCES `mydb`.`Passenger` (`Pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_FlightTime1`
    FOREIGN KEY (`FlightTime_Flight_no`)
    REFERENCES `mydb`.`FlightTime` (`Flight_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
